package com.example.geektrust;

public enum Relation {
    MOTHER, FATHER, CHILDREN, DAUGHTER, SON, SIBLING, SISTER, BROTHER, SISTER_IN_LAW, BROTHER_IN_LAW,
    MATERNAL_AUNT, MATERNAL_UNCLE, PATERNAL_AUNT, PATERNAL_UNCLE
}
